---
title: "Fern Taxonomy"
format:
  html:
    toc: true
  docx:
    toc: true
execute: 
  echo: false
  message: false
  warning: false
---

```{r}
#| label: setup
library(tidyverse)
library(gluedown)
```

```{r}
#| label: load-data
wf_dwc <- read_csv(here::here("working/wf_dwc.csv")) %>%
  mutate(order = 1:nrow(.) %>% as.numeric)
```

```{r}
#| label: headers
#| results: asis

# Need to add spacers between each level above species
spacers <-
  wf_dwc %>%
  filter(
    taxonRank %in% c("order", "family", "subfamily", "tribe,", "genus")) %>%
  transmute(taxonID, taxonRank = "spacer", order = order - 0.5)

syns <-
  wf_dwc %>%
  filter(taxonomicStatus == "synonym", taxonRank == "species") %>%
  mutate(syn_txt = glue::glue("= {scientificName} [{namePublishedIn}]")) %>%
  select(acceptedNameUsageID, syn_txt) %>%
  group_by(acceptedNameUsageID) %>%
  summarize(syn_txt = list(syn_txt))  %>%
  mutate(syn_txt = map(syn_txt, md_hardline)) %>%
  left_join(
    select(wf_dwc, taxonID, order),
    by = c(acceptedNameUsageID = "taxonID")
  ) %>%
  mutate(
    taxonomicStatus = "synonym",
    order = order + 0.1)

print_dat <-
wf_dwc %>%
    filter(taxonomicStatus == "accepted") %>%
    bind_rows(spacers) %>%
    bind_rows(syns) %>%
    arrange(order) %>%
    mutate(
     text = case_when(
       taxonRank == "order" ~ md_heading(scientificName, 2),
       taxonRank == "family" ~ md_heading(scientificName, 3),
       taxonRank == "subfamily" ~ md_heading(scientificName, 4),
       taxonRank == "tribe" ~ md_heading(scientificName, 5),
       taxonRank == "genus" ~ md_heading(scientificName, 6),
       taxonRank == "species" ~ md_bullet(md_hardline(scientificName)),
       taxonRank %in% c("form", "variety", "subspecies") ~ 
         md_bullet(scientificName),
       taxonRank == "spacer" ~ glue::glue("")
     )
   )

for (i in seq_len(nrow(print_dat))) {
  if (!is.null(print_dat$syn_txt[[i]])) {
    print(print_dat$syn_txt[[i]])
  } else {
    print(print_dat$text[[i]])
  }
}
```
